config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  # Session
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  resources :votes, only: ["create"]
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  has_many :votes, dependent: :destroy

  # def vote_balance
  #   vote_balance || 0
  # end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  after_create :update_vote_balance
  after_destroy :revert_vote

  belongs_to :user
  belongs_to :post

  validates :kind, presence: true
  validates :kind, uniqueness: {scope: [:post_id, :user_id]}

  def update_vote_balance
    balance = self.post.vote_balance || 0

    balance += 1 if self.kind == "up"
    balance -= 1 if self.kind == "down"

    self.post.update(vote_balance: balance);
  end

  def revert_vote
    balance = self.post.vote_balance || 0
    value = self.kind == "up" ? -1 : +1

    self.post.update(vote_balance: balance + value);
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_authentication

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def current_user
    user = User.find(session[:user_id]) if session[:user_id]
    @current_user ||= user
  end

  def logged_in?
    current_user != nil
  end

  def require_authentication
    redirect_to login_path unless logged_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_authentication
  
  def home
    @q = Post.ransack(params[:q])
    @posts = @q.result.paginate(page: params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: [:destroy, :show]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post cadastrado com sucesso"
      redirect_to post_path(@post)
    else
      flash.now[:warning] = "Erro ao cadastrar post"
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post excluído com sucesso"
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def load_post
    @post = Post.find(params[:id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_authentication

  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      reset_session
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Credenciais inválidas"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_authentication, only: [:show]
  
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.build(vote_params)

    if @vote.save
      flash[:success] = "Voto cadastrado com sucesso"
    else
      flash[:error] = "Erro ao cadastrar voto"
    end

    redirect_back(fallback_location: root_path)
  end

  def vote_params
    params.require(:vote).permit(:kind, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def post_link(name, sort_by, order = "desc")
    sort = {q: {s: ["#{sort_by} #{order}"]}}
    css_class = params["q"].try(:[], "s").try(:first).try(:include?, sort_by) ? "active item" : "item"
    link_to name, root_path(params: sort), {class: css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui secondary pointing fixed large menu">
      <%= post_link "Top", "vote_balance" %>
      <%= post_link "Recentes", "created_at" %>
      <%= link_to "Postar!", new_post_path, {class: "item"} %>
      <div class="right menu">
        <%= link_to "Entrar", login_path, {class: "item"} if current_user.nil? %>
        <%= link_to 'Sair', logout_path, method: :delete, data: { confirm: 'Sair?' }, class: 'item' unless current_user.nil? %>

        <!-- <a class="ui item">
          Logout
        </a> -->
      </div>
    </div>

    <div class="ui main container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/flash_messages", object: @post %>
<% @posts.each do |post| %>
  <div class="ui post segment">
    <div class="votes">
      <%= link_to votes_path(params: {vote: {kind: 'up', post_id: post.id}}), method: :post do %>
        <i class="arrow alternate up icon"></i>
      <% end %>
      <span><%= post.vote_balance %></span>
      <%= link_to votes_path(params: {vote: {kind: 'down', post_id: post.id}}), method: :post do %>
        <i class="arrow alternate down icon"></i>
      <% end %>
    </div>

    <div class="content">
      <div class="meta">
        <img src="<%= "https://robohash.org/#{post.user.username}" %>" alt="">
        <%= link_to post.user do %>
          <span><%= post.user.username %></span>
          <span class="time"> - <%= time_ago_in_words post.created_at %></span>
        <% end %>
      </div>

      <h2 class="ui header"><%= post.title %></h2>
      <div class="body"><%= post.body %></div>
    </div>

  </div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="sixteen wide column user-group-form">
  <%= render "shared/flash_messages", object: @post %>
  <%= form_for @post, :html => {class: "ui small form", multipart: true, "accept-charset": "UTF-8" } do |f| %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, :placeholder => "Título" %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div class="ui divider"></div>

    <div class="field">
      <%= submit_tag "Salvar", :class => "ui submit blue button" %>
      <% if @post.persisted? && @post.user_id == current_user.id %>
        <%= link_to post_path(@post), method: :delete, class: "bnt delete", data: { confirm: 'Tem certeza que deseja remover o post' } do %>
          <i class="trash icon"></i> Remover post
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="ui post segment">
  <div class="votes">
    <a href="#"><i class="arrow alternate up icon"></i></a>
    <span><%= @post.vote_balance %></span>
    <a href="#"><i class="arrow alternate down icon"></i></a>
  </div>

  <div class="content">
    <div class="meta">
      <img src="<%= "https://robohash.org/#{@post.user.username}" %>" alt="">
      <%= link_to @post.user do %>
        <span><%= @post.user.username %></span>
        <span class="time"> - <%= time_ago_in_words @post.created_at %></span>
      <% end %>
    </div>

    <h2 class="ui header"><%= @post.title %></h2>
    <div class="body"><%= @post.body %></div>

    <% if @post.user_id == current_user.try(:id) %>
      <%= link_to post_path(@post), method: :delete, class: "bnt delete", data: { confirm: 'Tem certeza que deseja remover o post' } do %>
        <i class="trash icon"></i> Remover post
      <% end %>
    <% end %>
  </div>

</div>

app/views/session/new.html.erb
<div class="ui vertically padded centered grid login">
  <div class="five wide computer twelve wide column">
    <%= render "shared/flash_messages", object: nil %>
    <div class="ui blue segment">
      <%= form_for login_path, html: {class: "ui form"} do |f| %>
        <div class="field">
          <%= text_field_tag :username, params[:username], :placeholder => "Nome de usuário"%>
        </div>
        <div class="field">
          <%= password_field_tag :password, params[:email], :placeholder => "Senha" %>
        </div>

        <div class="field">
          <%= submit_tag "Entrar", :class => "ui submit blue fluid button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, message| %>
    <div class="ui <%= type %> message">
      <i class="close icon"></i>
      <div class="header">
        <%= message %>
      </div>
      <% unless object.nil? %>
        <% unless object.errors.empty? %>
          <ul class="list">
            <% object.errors.each do |attr, msg| %>
              <li><%= "#{object.class.human_attribute_name(attr).capitalize} - #{msg}" %></li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  <% end  %>
<% end %>

app/views/users/show.html.erb
<div class="ui grid">
  <%= render "shared/flash_messages", object: @user %>
  <div class="four wide column">
    <div class="ui fluid card">
      <div class="image">
        <img src="<%= "https://robohash.org/#{@user.username}" %>" alt="">
      </div>
      <div class="content">
        <a class="header"><%= @user.username %></a>
        <div class="meta">
          <span class="date">Desde de: <%= @user.created_at.strftime("%d/%m/%Y") %></span>
        </div>
        <div class="description">
          <%= @user.bio %>
        </div>
      </div>
      <div class="extra content">
        <a>
          <i class="edit icon"></i>
          <%= @user.posts.count %> Posts
        </a>
      </div>
    </div>
  </div>

  <div class="twelve wide column">
    <% @user.posts.each do |post| %>
      <div class="ui post segment">
        <div class="votes">
          <span><%= post.vote_balance %></span>
        </div>

        <div class="content">
          <div class="meta">
            <img src="<%= "https://robohash.org/#{post.user.username}" %>" alt="">
            <%= link_to post.user do %>
              <span><%= post.user.username %></span>
              <span class="time"> - <%= time_ago_in_words post.created_at %></span>
            <% end %>
          </div>

          <h2 class="ui header"><%= post.title %></h2>
          <div class="body"><%= post.body %></div>
        </div>

      </div>
    <% end %>
  </div>
</div>